# Generated by Django 5.0.2 on 2024-03-09 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pcards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pcardname', models.CharField(max_length=50)),
                ('pcardcost', models.CharField(max_length=50)),
            ],
        ),
    ]
