# Generated by Django 5.0.2 on 2024-03-10 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_pcards_pcardimg'),
    ]

    operations = [
        migrations.AddField(
            model_name='pcards',
            name='pcarddiscount',
            field=models.CharField(default=5, max_length=50),
            preserve_default=False,
        ),
    ]
