# Generated by Django 5.0.2 on 2024-03-24 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_pcards_pcardrating'),
    ]

    operations = [
        migrations.CreateModel(
            name='productViewer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smallimg1', models.FileField(default=None, null=True, upload_to='app/')),
                ('mainimg', models.FileField(default=None, null=True, upload_to='app/')),
            ],
        ),
        migrations.AlterField(
            model_name='pcards',
            name='pcardrating',
            field=models.IntegerField(),
        ),
    ]
