# Generated by Django 5.0.2 on 2024-03-24 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_productviewer_alter_pcards_pcardrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='productviewer',
            name='smallimg2',
            field=models.FileField(default=None, null=True, upload_to='app/'),
        ),
        migrations.AddField(
            model_name='productviewer',
            name='smallimg3',
            field=models.FileField(default=None, null=True, upload_to='app/'),
        ),
        migrations.AddField(
            model_name='productviewer',
            name='smallimg4',
            field=models.FileField(default=None, null=True, upload_to='app/'),
        ),
    ]
