# Generated by Django 5.0.2 on 2024-03-25 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_productviewer_smallimg2_productviewer_smallimg3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productviewer',
            name='cutoffprice',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productviewer',
            name='discount',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productviewer',
            name='productdescription',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productviewer',
            name='productname',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productviewer',
            name='productprice',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
