# Generated by Django 5.0.2 on 2024-04-24 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_productviewer_cutoffprice_productviewer_discount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productviewer',
            old_name='id',
            new_name='product_id',
        ),
    ]
