# Generated by Django 5.0.2 on 2024-04-24 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_rename_id_productviewer_product_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pcards',
            old_name='id',
            new_name='product_id',
        ),
        migrations.RemoveField(
            model_name='productviewer',
            name='cutoffprice',
        ),
        migrations.RemoveField(
            model_name='productviewer',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='productviewer',
            name='productname',
        ),
        migrations.RemoveField(
            model_name='productviewer',
            name='productprice',
        ),
    ]
