# Generated by Django 5.0.2 on 2024-08-24 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='lname',
        ),
    ]
